sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "12.2.22"

before_install:
  - npm install -g --quiet mocha @angular/cli
  - npm link
